synchronise test directory

diff --git a/test/run_test b/test/run_test
--- a/test/run_test
+++ b/test/run_test
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Note on step return codes:
+#   0 = no problem
+#   1 to 9 = light problem, process can continue
+#   10 and more = serious problem, process should stop
+
+#----------------------------------------------------------------------------------------------------
+
 function FixmeCheck()
 {
 	output=`grep -RlI "FIXME" . 2> /dev/null  | grep -v "OLD\|.git\|.tex\|.log\|test/run_test"`
@@ -7,7 +14,7 @@ function FixmeCheck()
 	then
 		echo "There are FIXMEs in the code."
 		echo "<li>FAILED</li>" >> "$report"
-		return 1
+		return 10
 	fi
 
 	echo "<li>OK</li>" >> "$report"
@@ -25,6 +32,8 @@ function TodoCheck()
 	else
 		echo "<li>$n_TODO files affected</li>" >> "$report"
 	fi
+
+	return 0
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -45,13 +54,15 @@ function StaticAnalysisCheck()
 	else
 		echo "<li>report <a href=\"$index\">here</a></li>" >> "$report"
 	fi
+
+	return 0
 }
 
 #----------------------------------------------------------------------------------------------------
 
 function Compilation()
 {
-	make -j8 || return 1
+	make -j8 || return 10
 
 	echo "<li>OK</li>" >> "$report"
 }
@@ -60,42 +71,16 @@ function Compilation()
 
 function MainAnalysis()
 {
-	echo "<li>dataset: $ds</li>" >> "$report"
+	./configure.analysis -fast || return 10
 
-	./run -wait "distill.cc" "data/$ds" || return 10
-	./run -wait "distill.cc" "data/$ds" -danti || return 11
+	fd="${ds%/*}"
+	make -f "makefile.analysis" "data/$fd/.target" -j8 || 11
 
-	./run -wait "distributions.cc" "data/$ds" -O "-bootstrap 1 -details 5" || return 12
-
-	./run -wait "resolution_fit.cc" "data/$ds" || return 13
-
-	./run -wait "process_timber.cc" "data/$ds" || return 20
-
-	./run -wait "alignment.cc" "data/$ds" || return 21
-	./run -wait "alignment_fit.cc" "data/$ds" || return 22
-
-	./run -wait "eff3outof4.cc" "data/$ds" || return 23
-	./run -wait "eff3outof4_details.cc" "data/$ds" || return 24
-	./run -wait "eff3outof4_fit.cc" "data/$ds" || return 25
-
-	./run -wait "pileup.cc" "data/$ds/../ZeroBias" || return 26
-
-	#./run -wait "unfolding_cf_mc.cc" "data/$ds" || return 27
-	./run -wait "unfolding_cf_ni.cc" "data/$ds" || return 28
-
-	./run -wait "distributions_anti.cc" "data/$ds" -danti || return 29
-
-	./run -wait "distributions.cc" "data/$ds" || return 30
-
-	./run -wait "alignment_final.cc" "data/$ds" || return 31
-
-	data/merge -entry "data/$ds/,1,test,1" -output "data/merged.root" &> "data/merge.log" || return 40
-
-	cd "studies/systematics"
-	./run_all "1E6" || return 50
-	cd - &> /dev/null
+	data/merge -entry "data/$ds/,1,test,1" -output "data/merged.root" &> "data/merge.log" || return 12
 
 	echo "<li>OK</li>" >> "$report"
+
+	return 0
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -157,7 +142,7 @@ function MainAnalysisComparison()
 {
 	ResetComparisonResults
 
-	if [ "$reference_directory" == "none" ]
+	if [[ "$reference_directory" == *"none" ]]
 	then
 		echo "<li>not run - missing reference</li>" >> "$report"
 
@@ -219,6 +204,56 @@ function MainAnalysisComparison()
 
 		MakeOneComparison "data/merged.root" "eb/merged/combined/h_dsdt" "global"
 
+		if [ "$n_diff" -eq "0" ]
+		then
+			echo "<li>OK</li>" >> "$report"
+		else
+			echo "<li>$n_diff differences:</li>" >> "$report"
+			echo "<ul>" >> "$report"
+			echo -e "$failed_comparisons" >> "$report"
+			echo "</ul>" >> "$report"
+
+			return 2
+		fi
+	fi
+
+	return 0
+}
+
+#----------------------------------------------------------------------------------------------------
+
+function Studies()
+{
+	cd "studies/reconstruction_formulae"
+	./run_all || return 10
+	cd - &> /dev/null
+
+	cd "studies/systematics"
+	./run_all "1E6" || return 11
+	cd - &> /dev/null
+
+	echo "<li>OK</li>" >> "$report"
+
+	return 0
+}
+
+#----------------------------------------------------------------------------------------------------
+
+function StudiesComparison()
+{
+	ResetComparisonResults
+
+	if [[ "$reference_directory" == *"none" ]]
+	then
+		echo "<li>not run - missing reference</li>" >> "$report"
+
+		return 1
+	else
+		MakeOneComparison "studies/reconstruction_formulae/test_formulae_graph.root" "theta_x_one_arm_regr, th_x_L/pitch,beamDiv,vertex/g_stddev" "global"
+		MakeOneComparison "studies/reconstruction_formulae/test_formulae_graph.root" "theta_x_two_arm_regr_LRavg, th_x/pitch,beamDiv,vertex/g_stddev" "global"
+		MakeOneComparison "studies/reconstruction_formulae/test_formulae_graph.root" "theta_y_one_arm_regr, th_y_L/pitch,beamDiv,vertex/g_stddev" "global"
+		MakeOneComparison "studies/reconstruction_formulae/test_formulae_graph.root" "theta_y_two_arm_regr_LRavg, th_y/pitch,beamDiv,vertex/g_stddev" "global"
+
 		MakeOneComparison "studies/systematics/matrix.root" "matrices/all-but-norm/eb/h_stddev" "global"
 		MakeOneComparison "studies/systematics/matrix.root" "matrices/all/eb/h_stddev" "global"
 
@@ -234,6 +269,8 @@ function MainAnalysisComparison()
 			return 2
 		fi
 	fi
+
+	return 0
 }
 
 #----------------------------------------------------------------------------------------------------
@@ -249,6 +286,8 @@ steps="
  Compilation
  MainAnalysis
  MainAnalysisComparison
+ Studies
+ StudiesComparison
 "
 reference_directory=""
 report="test.log_short.html"
@@ -296,13 +335,14 @@ rm -f "$report"
 	echo "<ul>"
 	echo "<li>starting test at: $(pwd -P)</li>"
 	echo "<li>reference directory: $reference_directory</li>"
+	echo "<li>test dataset: $ds</li>" >> "$report"
 ) >> "$report"
 
 # prepare environment
 source environment || exit 1
 
 # run steps
-failure="False"
+failure="0"
 for step in $steps
 do
 	echo "----- $step --------------------------------------------------"
@@ -311,10 +351,18 @@ do
 	echo "<ul>" >> "$report"
 
 	$step
-	if [ "$?" -ne "0" ]
+	rc="$?"
+	if [ "$rc" -ne "0" ]
 	then
-		failure="True"
-		break
+		echo "<li>finished with return code $rc</li>" >> "$report"
+
+		failure="1"
+
+		if [ "$rc" -gt 9 ]
+		then
+			failure="10"
+			break
+		fi
 	fi
 
 	echo "</ul>" >> "$report"
@@ -327,7 +375,4 @@ done
 	echo "</html>"
 ) >> "$report"
 
-if [ "$failure" == "True" ]
-then
-	exit 10
-fi
+exit $failure
