add more comparisons

diff --git a/test/run_test b/test/run_test
--- a/test/run_test
+++ b/test/run_test
@@ -5,7 +5,7 @@ reference_directory="$1"
 if [ -z "$reference_directory" ]
 then
 	reference_directory=`ls -d ../IB/4rp/*/|head -n 1`
-	echo "* sitting default reference directory: $reference_directory"
+	echo "* setting default reference directory: $reference_directory"
 fi
 
 log_short="$2"
@@ -95,6 +95,7 @@ echo "* analysis check OK" >> "$log_short"
 echo "-------------------- RUNNING COMPARISON --------------------"
 
 n_diff="0"
+failed_comparisons=""
 
 function MakeOneComparison()
 {
@@ -103,23 +104,76 @@ function MakeOneComparison()
 
 	test/compare \
 		"./data/$ds/$file" "$obj" \
-		"$reference_directory/data/$ds/$file" "$obj" || let n_diff+=1
+		"$reference_directory/data/$ds/$file" "$obj"
+
+	if [ ! "$?" -eq "0" ]
+	then
+		let n_diff+=1
+		failed_comparisons="${failed_comparisons}  - $file, $obj\n"
+	fi
 }
 
 if [ "$reference_directory" == "none" ]
 then
 	echo "* comparison not run (missing reference)" >> "$log_short"
 else
+	MakeOneComparison "alignment.root" "global/L_1_F/a"
+	MakeOneComparison "alignment.root" "global/L_1_F/b"
+	MakeOneComparison "alignment.root" "global/L_1_F/c"
+	MakeOneComparison "alignment.root" "global/R_2_F/a"
+	MakeOneComparison "alignment.root" "global/R_2_F/b"
+	MakeOneComparison "alignment.root" "global/R_2_F/c"
+
+	# TODO: alignment_final
+
+	MakeOneComparison "alignment_fit.root" "L_2_F/a_fit"
+	MakeOneComparison "alignment_fit.root" "L_2_F/b_fit"
+	MakeOneComparison "alignment_fit.root" "L_2_F/c_fit"
+	MakeOneComparison "alignment_fit.root" "R_1_F/a_fit"
+	MakeOneComparison "alignment_fit.root" "R_1_F/b_fit"
+	MakeOneComparison "alignment_fit.root" "R_1_F/c_fit"
+
 	MakeOneComparison "distributions_45b_56t.root" "acceptance correction/eb/h_t_after"
 	MakeOneComparison "distributions_45t_56b.root" "acceptance correction/eb/h_t_after"
+	MakeOneComparison "distributions_45b_56t.root" "normalization+unfolding/eb/h_t_normalized_unsmeared"
+	MakeOneComparison "distributions_45t_56b.root" "normalization+unfolding/eb/h_t_normalized_unsmeared"
 
 	MakeOneComparison "distributions_anti_45b_56b.root" "acceptance correction/eb/h_t_after"
 	MakeOneComparison "distributions_anti_45t_56t.root" "acceptance correction/eb/h_t_after"
+
+	MakeOneComparison "eff3outof4_45b_56t.root" "excluded RPs L_2_F/n_si 3.0/th_y dependence/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_45b_56t.root" "excluded RPs R_1_F/n_si 3.0/th_y dependence/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_45t_56b.root" "excluded RPs L_2_F/n_si 3.0/th_y dependence/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_45t_56b.root" "excluded RPs R_1_F/n_si 3.0/th_y dependence/h_refined_ratio.th_y"
+
+	MakeOneComparison "eff3outof4_details.root" "45b_56t/L_1_F/track/th_y : rel"
+	MakeOneComparison "eff3outof4_details.root" "45b_56t/R_2_F/track/th_y : rel"
+	MakeOneComparison "eff3outof4_details.root" "45t_56b/L_1_F/track/th_y : rel"
+	MakeOneComparison "eff3outof4_details.root" "45t_56b/R_2_F/track/th_y : rel"
+
+	MakeOneComparison "eff3outof4_fit.root" "45b_56t/L_2_F/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_fit.root" "45b_56t/L_1_F/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_fit.root" "45b_56t/R_1_F/h_refined_ratio.th_y"
+	MakeOneComparison "eff3outof4_fit.root" "45b_56t/R_2_F/h_refined_ratio.th_y"
+
+	MakeOneComparison "pileup_combined.root" "45b_56t/dgn/pat_suff_destr && pat_suff_destr, L || R/rel"
+	MakeOneComparison "pileup_combined.root" "45t_56b/dgn/pat_suff_destr && pat_suff_destr, L || R/rel"
+
+	MakeOneComparison "resolution_fit_45b_56t.root" "d_x/g_fits"
+	MakeOneComparison "resolution_fit_45b_56t.root" "d_y/g_fits"
+	MakeOneComparison "resolution_fit_45t_56b.root" "d_x/g_fits"
+	MakeOneComparison "resolution_fit_45t_56b.root" "d_y/g_fits"
+
+	MakeOneComparison "unfolding_cf_ni_45b_56t.root" "fit-1/eb"
+	MakeOneComparison "unfolding_cf_ni_45t_56b.root" "fit-1/eb"
+
+	# TODO: check for merge
 
 	if [ "$n_diff" -eq "0" ]
 	then
 		echo "* comparison OK" >> "$log_short"
 	else
-		echo "* comparison: $n_diff differences" >> "$log_short"
+		echo "* comparison: $n_diff differences:" >> "$log_short"
+		echo -e "$failed_comparisons" >> "$log_short"
 	fi
 fi
